# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2

# Dependencies
fabric_version=0.133.14+1.21.9
modmenu_version=16.0.0-rc.1
trinkets_version=7c116b1dce
cardinal_components_version=6.3.0

#malilib
malilib_version = 0.26.1
minecraft_version_out = 1.21.9

# Mod Properties
mod_version=1.21.9-1.12.2
maven_group=de.guntram.mcmod
archives_base_name=durabilityviewer

#Modrinth
modrinth_id = WnbN2C6I


