# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.18.5

# Dependencies
fabric_version=0.144.3+26.1
modmenu_version=18.0.0-alpha.8
trinkets_version=866017277f
cardinal_components_version=6.3.0

#malilib
malilib_version = 0.28.1
minecraft_version_out = 26.1

# Mod Properties
mod_version=26.1-1.12.4
maven_group=de.guntram.mcmod
archives_base_name=durabilityviewer

#Modrinth
modrinth_id = WnbN2C6I


